type Friend {
  id: ID!
  username: String!
  profile_image: ProfileImage
  full_name: String!
}

type ProfileImage {
  url: String!
  publicId: String!
}

type Subscription {
  friendReqNotification(user_id: ID!): Friend!
}
